facebook_login:
    pattern: /facebook_login
    defaults: { _controller: FlorProjectUserBundle:OAuth:facebookLogin }

welcome_facebook_user:
    pattern: /welcome_facebook_user
    defaults: { _controller: FlorProjectUserBundle:OAuth:welcomeFacebookUser }
